const CONFIG={currentLeagueId:"1341763186407276544",leagueIds:["1341763186407276544","1212553673821929472","1138349648558624768"],api:"https://api.sleeper.app/v1",roundsToCheck:60};
const state={league:null,currentUsers:[],currentRosters:[],managers:new Map(),trades:[],selectedWindow:"14",players:{}};const $=id=>document.getElementById(id);const WL={"14":"14 days","28":"28 days","90":"90 days","all":"All time"};
async function getJSON(url,optional=false){try{const r=await fetch(url);if(!r.ok)throw new Error(r.status);return await r.json()}catch(e){if(optional)return null;throw e}}
async function limitedMap(items,limit,fn){const out=new Array(items.length);let n=0;async function run(){while(n<items.length){let i=n++;try{out[i]=await fn(items[i])}catch{out[i]=[]}}}await Promise.all(Array.from({length:limit},run));return out}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function fmt(ts,short=false){return ts?new Intl.DateTimeFormat("en-AU",short?{day:"numeric",month:"short"}:{day:"numeric",month:"short",year:"numeric"}).format(new Date(ts)):"Unknown"}
function buildManagers(){const u=Object.fromEntries(state.currentUsers.map(x=>[x.user_id,x]));state.managers.clear();state.currentRosters.forEach(r=>{const x=u[r.owner_id]||{};const name=x.metadata?.team_name||x.display_name||`Team ${r.roster_id}`;state.managers.set(String(r.owner_id),{id:String(r.owner_id),name,roster:r,initials:name.split(/\s+/).slice(0,2).map(z=>z[0]).join("").toUpperCase()})})}
function mids(t){return [...new Set((t.manager_ids||[]).map(String))].filter(id=>state.managers.has(id))}function tradesFor(w){if(w==="all")return state.trades;return state.trades.filter(t=>(t.created||0)>=Date.now()-Number(w)*864e5)}
function counts(w){const c=Object.fromEntries([...state.managers.keys()].map(id=>[id,0]));tradesFor(w).forEach(t=>mids(t).forEach(id=>c[id]++));return c}function ranked(w){const c=counts(w);return [...state.managers.values()].map(m=>({...m,count:c[m.id]||0})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name))}
function rosterMetric(r,key){return Number(r.settings?.[key]||0)}function points(r){return rosterMetric(r,"fpts")+rosterMetric(r,"fpts_decimal")/100}function record(r){return {w:rosterMetric(r,"wins"),l:rosterMetric(r,"losses"),t:rosterMetric(r,"ties")}}
function powerData(){const arr=[...state.managers.values()].map(m=>{const rec=record(m.roster);const games=Math.max(rec.w+rec.l+rec.t,1),wp=(rec.w+.5*rec.t)/games,pts=points(m.roster);return {...m,wp,pts,raw:wp*60+pts/Math.max(...[...state.managers.values()].map(x=>points(x.roster)),1)*40}}).sort((a,b)=>b.raw-a.raw);const max=arr[0]?.raw||1;return arr.map((x,i)=>({...x,score:Math.round(x.raw/max*100),rank:i+1}))}
function renderSummary(){const w=state.selectedWindow,r=ranked(w),ts=tradesFor(w),active=r.filter(x=>x.count).length,total=r.reduce((a,x)=>a+x.count,0),lead=r[0];$("leagueTrades").textContent=ts.length;$("leagueTradesLabel").textContent=w==="all"?`${CONFIG.leagueIds.length} seasons combined`:`Last ${w} days`;$("activeTeams").textContent=active;$("averageTrades").textContent=state.managers.size?(total/state.managers.size).toFixed(1):"0.0";$("leaderName").textContent=lead?.name||"—";$("leaderTrades").textContent=lead?.count||0;$("leaderWindow").textContent=WL[w];$("rankingWindow").textContent=WL[w];const latest=state.trades[0];$("latestTradeShort").textContent=latest?`${mids(latest).length}-team`:"—";$("latestTradeDate").textContent=latest?fmt(latest.created):"No trade"}
function renderLeaderboard(){const r=ranked(state.selectedWindow),max=Math.max(...r.map(x=>x.count),1);$("leaderboard").classList.remove("loading");$("leaderboard").innerHTML=r.map((x,i)=>`<div class="leader-row"><span class="rank">${i+1}</span><span class="team-name">${esc(x.name)}</span><div class="bar-track"><div class="bar-fill" style="width:${x.count/max*100}%"></div></div><span class="trade-count">${x.count}</span></div>`).join("")}
function renderPower(){const p=powerData();$("powerRankings").classList.remove("loading");$("powerRankings").innerHTML=p.map(x=>{const rec=record(x.roster);return `<div class="rank-item"><b>${x.rank}</b><div><strong>${esc(x.name)}</strong><div class="meta">${rec.w}-${rec.l} · ${points(x.roster).toFixed(1)} pts</div></div><span class="power-score">${x.score}</span></div>`}).join("")}
function renderOdds(){const p=powerData();let weights=p.map(x=>Math.exp((x.score-70)/18)),sum=weights.reduce((a,b)=>a+b,0);let rows=p.map((x,i)=>({...x,prob:weights[i]/sum}));$("championshipOdds").classList.remove("loading");$("championshipOdds").innerHTML=rows.map((x,i)=>`<div class="odds-row"><b>${i+1}</b><div><strong>${esc(x.name)}</strong>${i===0?'<div class="favourite">FAVOURITE</div>':''}</div><span class="odds">$${Math.max(1.01,1/x.prob*.88).toFixed(2)}</span></div>`).join("")}
function playerName(id){return state.players[id]?.full_name||state.players[id]?.first_name||`Player ${id}`}
function rankValue(id){const p=state.players[id]||{};return Number(p.search_rank||p.fantasy_positions?.length?500:800)}
function tradeSides(t){const by={};mids(t).forEach(id=>by[id]=[]);Object.entries(t.adds||{}).forEach(([pid,rid])=>{const mid=t.roster_owner_map?.[String(rid)];if(mid&&by[mid])by[mid].push(pid)});return by}
function tradeScore(t){const sides=tradeSides(t);const vals=Object.values(sides).map(ids=>ids.reduce((s,id)=>s+1/Math.max(rankValue(id),1),0));return vals.length?Math.max(...vals)*100000:0}
function renderTradeWeek(){const week=state.trades.filter(t=>t.created>=Date.now()-7*864e5);const pool=week.length?week:state.trades.slice(0,12);const t=[...pool].sort((a,b)=>tradeScore(b)-tradeScore(a))[0];if(!t){$("tradeOfWeek").innerHTML="No trade available";return}const sides=tradeSides(t),entries=Object.entries(sides).slice(0,2);const html=entries.map(([mid,ids])=>`<div class="trade-side"><strong>${esc(state.managers.get(mid)?.name||"Former manager")} receives</strong>${ids.length?ids.map(id=>`<div class="trade-player"><span>${esc(playerName(id))}</span><span class="rank-badge">Rank #${rankValue(id)}</span></div>`).join(""):'<div class="trade-player"><span>Draft picks / assets</span></div>'}</div>`);$("tradeOfWeek").classList.remove("loading");$("tradeOfWeek").innerHTML=`<div class="trade-feature">${html[0]||""}<div class="trade-arrow">⇄</div>${html[1]||""}<div class="trade-score"><span>IMO TRADE SCORE</span><strong>${Math.round(tradeScore(t))}</strong><small>${fmt(t.created)}</small></div></div>`}
function renderHeatmap(){const ms=[...state.managers.values()],mat={};state.trades.forEach(t=>{const ids=mids(t);for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const k=[ids[i],ids[j]].sort().join("|");mat[k]=(mat[k]||0)+1}});const max=Math.max(...Object.values(mat),1);let h='<table class="heatmap"><tr><th></th>'+ms.map(m=>`<th title="${esc(m.name)}">${esc(m.initials)}</th>`).join('')+'</tr>';ms.forEach(a=>{h+=`<tr><th>${esc(a.initials)}</th>`+ms.map(b=>{if(a.id===b.id)return'<td>—</td>';const v=mat[[a.id,b.id].sort().join('|')]||0,l=v?Math.min(4,Math.ceil(v/max*4)):0;return `<td class="${l?'heat-'+l:''}" title="${esc(a.name)} × ${esc(b.name)}: ${v}">${v||''}</td>`}).join('')+'</tr>'});$("tradeHeatmap").classList.remove("loading");$("tradeHeatmap").innerHTML=h+'</table>'}
function renderCalendar(){const by={};state.trades.forEach(t=>{const d=new Date(t.created);d.setHours(0,0,0,0);by[d.getTime()]=(by[d.getTime()]||0)+1});const start=new Date();start.setDate(start.getDate()-364);start.setHours(0,0,0,0);const days=[];for(let i=0;i<365;i++){const d=new Date(start);d.setDate(d.getDate()+i);const v=by[d.getTime()]||0,l=v?Math.min(4,v):0;days.push(`<span class="day ${l?'l'+l:''}" title="${fmt(d.getTime())}: ${v} trade${v===1?'':'s'}"></span>`)}$("activityCalendar").classList.remove("loading");$("activityCalendar").innerHTML=`<div class="calendar">${days.join('')}</div>`}
function renderBlock(){const moved={};state.trades.forEach(t=>Object.keys(t.adds||{}).forEach(id=>moved[id]=(moved[id]||0)+1));const rows=Object.entries(moved).sort((a,b)=>b[1]-a[1]).slice(0,8);$("tradeBlock").classList.remove("loading");$("tradeBlock").innerHTML=rows.length?rows.map(([id,n],i)=>`<div class="rank-item"><b>${i+1}</b><div><strong>${esc(playerName(id))}</strong><div class="meta">Most frequently moved assets</div></div><span class="power-score">${n}x</span></div>`).join(''):'<div class="loading">No player movement yet</div>'}
function longestDrought(){const r=ranked('all');return [...r].sort((a,b)=>a.count-b.count)[0]}
function renderRecords(){const biggest=[...state.trades].sort((a,b)=>(Object.keys(b.adds||{}).length+(b.draft_picks||[]).length)-(Object.keys(a.adds||{}).length+(a.draft_picks||[]).length))[0];const day={};state.trades.forEach(t=>{const k=new Date(t.created).toDateString();day[k]=(day[k]||0)+1});const peak=Object.entries(day).sort((a,b)=>b[1]-a[1])[0]||['—',0],all=ranked('all'),active=all[0],drought=longestDrought();const cards=[['Most active ever',active?.name||'—',`${active?.count||0} trades`],['Largest trade',biggest?`${Object.keys(biggest.adds||{}).length} players + ${(biggest.draft_picks||[]).length} picks`:'—',biggest?fmt(biggest.created):''],['Most trades in one day',`${peak[1]} trades`,peak[0]],['Longest trade drought',drought?.name||'—',`${drought?.count||0} all-time trades`]];$("leagueRecords").classList.remove("loading");$("leagueRecords").innerHTML=cards.map(x=>`<div class="record"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></div>`).join('')}
function renderTable(){const ws=['14','28','90','all'],cs=Object.fromEntries(ws.map(w=>[w,counts(w)])),r=ranked(state.selectedWindow),max=Object.fromEntries(ws.map(w=>[w,Math.max(...Object.values(cs[w]),0)]));$("scorecardBody").innerHTML=r.map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.name)}</b></td>${ws.map(w=>`<td class="${cs[w][x.id]===max[w]&&max[w]>0?'top-value':''}">${cs[w][x.id]||0}</td>`).join('')}</tr>`).join('')}
function renderRecent(){const r=state.trades.slice(0,10);$("recentTrades").classList.remove("loading");$("recentTrades").innerHTML=r.map(t=>`<article class="trade-card"><div class="trade-date">${fmt(t.created)} · ${esc(t.season_label||'')}</div><div class="trade-teams">${mids(t).map(id=>esc(state.managers.get(id)?.name||'Former manager')).join(' ↔ ')}</div><div class="trade-meta">${Object.keys(t.adds||{}).length} player moves · ${(t.draft_picks||[]).length} picks</div></article>`).join('')||'<div class="loading">No trades</div>'}
function renderAll(){renderSummary();renderLeaderboard();renderPower();renderOdds();renderTradeWeek();renderHeatmap();renderCalendar();renderBlock();renderRecords();renderTable();renderRecent()}
async function loadSeason(id){const [league,users,rosters]=await Promise.all([getJSON(`${CONFIG.api}/league/${id}`,true),getJSON(`${CONFIG.api}/league/${id}/users`,true),getJSON(`${CONFIG.api}/league/${id}/rosters`,true)]);if(!league||!users||!rosters)return null;const ownerByRoster={};rosters.forEach(r=>{if(r.owner_id!=null)ownerByRoster[String(r.roster_id)]=String(r.owner_id)});const rounds=Array.from({length:CONFIG.roundsToCheck},(_,i)=>i+1),b=await limitedMap(rounds,6,async wk=>{const x=await getJSON(`${CONFIG.api}/league/${id}/transactions/${wk}`,true);return (x||[]).filter(t=>t.type==='trade'&&(!t.status||t.status==='complete')).map(t=>{const ids=new Set((t.roster_ids||[]).map(String));Object.values(t.adds||{}).forEach(x=>ids.add(String(x)));Object.values(t.drops||{}).forEach(x=>ids.add(String(x)));(t.draft_picks||[]).forEach(p=>{if(p.owner_id!=null)ids.add(String(p.owner_id));if(p.previous_owner_id!=null)ids.add(String(p.previous_owner_id))});return {...t,manager_ids:[...ids].map(r=>ownerByRoster[r]).filter(Boolean),roster_owner_map:ownerByRoster,season_label:`${league.season} season`,league_id:id}})});return{league,users,rosters,trades:b.flat()}}
async function load(){$("refreshBtn").disabled=true;$("statusText").textContent='Connecting to Sleeper…';try{const [bundles,players]=await Promise.all([Promise.all(CONFIG.leagueIds.map(loadSeason)),getJSON(`${CONFIG.api}/players/nba`,true)]);const valid=bundles.filter(Boolean),cur=valid.find(x=>String(x.league.league_id)===CONFIG.currentLeagueId)||valid[0];state.league=cur.league;state.currentUsers=cur.users;state.currentRosters=cur.rosters;state.players=players||{};buildManagers();const u=new Map();valid.flatMap(x=>x.trades).forEach(t=>u.set(t.transaction_id||`${t.league_id}-${t.created}`,t));state.trades=[...u.values()].sort((a,b)=>(b.created||0)-(a.created||0));renderAll();$("statusText").textContent=`Live · ${valid.length} seasons loaded`}catch(e){console.error(e);$("statusText").textContent='Could not load Sleeper data'}finally{$("refreshBtn").disabled=false}}
document.querySelectorAll('.window-btn').forEach(b=>b.addEventListener('click',()=>{state.selectedWindow=b.dataset.window;document.querySelectorAll('.window-btn').forEach(x=>x.classList.toggle('active',x===b));renderSummary();renderLeaderboard();renderTable()}));$("refreshBtn").addEventListener('click',load);load();