const CONFIG={currentLeagueId:"1341763186407276544",leagueIds:["1341763186407276544","1212553673821929472","1138349648558624768"],api:"https://api.sleeper.app/v1",roundsToCheck:60,bookmakerMargin:1.08,oddsBaseline:0.25,oddsExponent:2,maxDisplayedOdds:51};
const state={league:null,currentUsers:[],currentRosters:[],managers:new Map(),trades:[],selectedWindow:"14",players:{},bundles:[],modelBundle:null,playerAverages:{},previousPowerRanks:{}};
const $=id=>document.getElementById(id),WL={"14":"14 days","28":"28 days","90":"90 days","all":"All time"};
async function getJSON(url,optional=false){try{const r=await fetch(url);if(!r.ok)throw new Error(r.status);return await r.json()}catch(e){if(optional)return null;throw e}}
async function limitedMap(items,limit,fn){const out=new Array(items.length);let n=0;async function run(){while(n<items.length){const i=n++;try{out[i]=await fn(items[i])}catch{out[i]=null}}}await Promise.all(Array.from({length:limit},run));return out}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function fmt(ts,short=false){return ts?new Intl.DateTimeFormat("en-AU",short?{day:"numeric",month:"short"}:{day:"numeric",month:"short",year:"numeric"}).format(new Date(ts)):"Unknown"}
function buildManagers(){const users=Object.fromEntries(state.currentUsers.map(x=>[x.user_id,x]));state.managers.clear();state.currentRosters.forEach(r=>{const u=users[r.owner_id]||{},name=u.metadata?.team_name||u.display_name||`Team ${r.roster_id}`;state.managers.set(String(r.owner_id),{id:String(r.owner_id),name,roster:r,initials:name.split(/\s+/).slice(0,2).map(z=>z[0]).join("").toUpperCase()})})}
function mids(t){return [...new Set((t.manager_ids||[]).map(String))].filter(id=>state.managers.has(id))}
function tradesFor(w){return w==="all"?state.trades:state.trades.filter(t=>(t.created||0)>=Date.now()-Number(w)*864e5)}
function counts(w){const c=Object.fromEntries([...state.managers.keys()].map(id=>[id,0]));tradesFor(w).forEach(t=>mids(t).forEach(id=>c[id]++));return c}
function ranked(w){const c=counts(w);return [...state.managers.values()].map(m=>({...m,count:c[m.id]||0})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name))}
function meaningfulWeeks(bundle){return [...new Set(bundle.matchups.filter(x=>Number(x.points)>0).map(x=>x.week))].sort((a,b)=>a-b)}
function selectModelBundle(){const current=state.bundles.find(b=>String(b.league.league_id)===CONFIG.currentLeagueId);if(current&&meaningfulWeeks(current).length>=2)return current;return state.bundles.filter(b=>meaningfulWeeks(b).length).sort((a,b)=>Number(b.league.season)-Number(a.league.season))[0]||current||state.bundles[0]}
function matchupRows(bundle,throughWeek=Infinity){return bundle.matchups.filter(x=>x.week<=throughWeek&&Number.isFinite(Number(x.points)))}
function managerMatchups(bundle,managerId,throughWeek=Infinity){return matchupRows(bundle,throughWeek).filter(x=>bundle.ownerByRoster[String(x.roster_id)]===String(managerId)).sort((a,b)=>a.week-b.week)}
function outcomesForBundle(bundle,throughWeek=Infinity){const rows=matchupRows(bundle,throughWeek),byWeek={};rows.forEach(x=>{(byWeek[x.week]??=[]).push(x)});const out={};Object.values(byWeek).forEach(weekRows=>{const groups={};weekRows.forEach(x=>{if(x.matchup_id!=null)(groups[x.matchup_id]??=[]).push(x)});Object.values(groups).forEach(g=>{if(g.length<2)return;const max=Math.max(...g.map(x=>Number(x.points)||0)),ties=g.filter(x=>(Number(x.points)||0)===max).length;g.forEach(x=>{const owner=bundle.ownerByRoster[String(x.roster_id)];if(!owner)return;(out[owner]??=[]).push({week:x.week,points:Number(x.points)||0,result:(Number(x.points)||0)===max?(ties>1?0.5:1):0})})})});return out}
function minMax(value,values,higher=true){const nums=values.filter(Number.isFinite),min=Math.min(...nums),max=Math.max(...nums);if(!nums.length||max===min)return .5;const n=(value-min)/(max-min);return higher?n:1-n}
function standingsTable(bundle,throughWeek=Infinity){const outcomes=outcomesForBundle(bundle,throughWeek);return [...state.managers.values()].map(m=>{const games=outcomes[m.id]||[],wins=games.reduce((s,g)=>s+g.result,0),pts=games.reduce((s,g)=>s+g.points,0);return {...m,wins,games:games.length,pts}}).sort((a,b)=>b.wins-a.wins||b.pts-a.pts||a.name.localeCompare(b.name)).map((x,i)=>({...x,standingRank:i+1}))}
function modelRows(bundle,throughWeek=Infinity,mode="power"){const standings=standingsTable(bundle,throughWeek),outcomes=outcomesForBundle(bundle,throughWeek),teamCount=Math.max(standings.length,1);const raw=standings.map(team=>{const games=outcomes[team.id]||[],formN=mode==="odds"?5:3,recent=games.slice(-formN),last5=games.slice(-5),form=recent.length?recent.reduce((s,g)=>s+g.result,0)/recent.length:0,avg5=last5.length?last5.reduce((s,g)=>s+g.points,0)/last5.length:0,ladder=teamCount===1?1:1-(team.standingRank-1)/(teamCount-1);return {...team,form,avg5,ladder}});const avgs=raw.map(x=>x.avg5);return raw.map(x=>{const avgNorm=minMax(x.avg5,avgs,true);const score=mode==="odds"?x.form*.50+avgNorm*.25+x.ladder*.25:x.ladder*.35+x.form*.35+avgNorm*.30;return {...x,score}}).sort((a,b)=>b.score-a.score||b.avg5-a.avg5||a.name.localeCompare(b.name)).map((x,i)=>({...x,rank:i+1}))}
function prepareModels(){state.modelBundle=selectModelBundle();const weeks=meaningfulWeeks(state.modelBundle),lastWeek=weeks.at(-1)||Infinity,priorWeek=weeks.length>1?weeks.at(-2):lastWeek;state.previousPowerRanks=Object.fromEntries(modelRows(state.modelBundle,priorWeek,"power").map(x=>[x.id,x.rank]));state.playerAverages=buildPlayerAverages(state.modelBundle,lastWeek)}
function buildPlayerAverages(bundle,throughWeek=Infinity){const sums={},games={};matchupRows(bundle,throughWeek).forEach(row=>{Object.entries(row.players_points||{}).forEach(([id,v])=>{const pts=Number(v);if(!Number.isFinite(pts))return;sums[id]=(sums[id]||0)+pts;games[id]=(games[id]||0)+1})});return Object.fromEntries(Object.keys(sums).map(id=>[id,games[id]?sums[id]/games[id]:0]))}
function renderSummary(){const w=state.selectedWindow,r=ranked(w),ts=tradesFor(w),active=r.filter(x=>x.count).length,total=r.reduce((a,x)=>a+x.count,0),lead=r[0],latest=state.trades[0];$("leagueTrades").textContent=ts.length;$("leagueTradesLabel").textContent=w==="all"?`${CONFIG.leagueIds.length} seasons combined`:`Last ${w} days`;$("activeTeams").textContent=active;$("averageTrades").textContent=state.managers.size?(total/state.managers.size).toFixed(1):"0.0";$("leaderName").textContent=lead?.name||"—";$("leaderTrades").textContent=lead?.count||0;$("leaderWindow").textContent=WL[w];$("rankingWindow").textContent=WL[w];$("latestTradeShort").textContent=latest?`${mids(latest).length}-team`:"—";$("latestTradeDate").textContent=latest?fmt(latest.created):"No trade"}
function renderLeaderboard(){const r=ranked(state.selectedWindow),max=Math.max(...r.map(x=>x.count),1);$("leaderboard").classList.remove("loading");$("leaderboard").innerHTML=r.map((x,i)=>`<div class="leader-row"><span class="rank">${i+1}</span><span class="team-name">${esc(x.name)}</span><div class="bar-track"><div class="bar-fill" style="width:${x.count/max*100}%"></div></div><span class="trade-count">${x.count}</span></div>`).join("")}
function renderPower(){const weeks=meaningfulWeeks(state.modelBundle),through=weeks.at(-1)||Infinity,p=modelRows(state.modelBundle,through,"power");$("powerRankings").classList.remove("loading");$("powerRankings").innerHTML=p.map(x=>{const old=state.previousPowerRanks[x.id]??x.rank,diff=old-x.rank,arrow=diff>0?`<span class="movement up">▲ ${diff}</span>`:diff<0?`<span class="movement down">▼ ${Math.abs(diff)}</span>`:`<span class="movement flat">—</span>`;return `<div class="rank-item power-row"><b>${x.rank}</b><strong>${esc(x.name)}</strong>${arrow}</div>`}).join("")}
function renderOdds(){const weeks=meaningfulWeeks(state.modelBundle),through=weeks.at(-1)||Infinity,rows=modelRows(state.modelBundle,through,"odds");const strengths=rows.map(x=>Math.pow(CONFIG.oddsBaseline+(1-CONFIG.oddsBaseline)*Math.max(0,Math.min(1,x.score)),CONFIG.oddsExponent)),sum=strengths.reduce((a,b)=>a+b,0)||1;const priced=rows.map((x,i)=>({...x,fairProb:strengths[i]/sum}));$("championshipOdds").classList.remove("loading");$("championshipOdds").innerHTML=priced.map((x,i)=>{const marketProb=Math.min(.99,x.fairProb*CONFIG.bookmakerMargin),rawOdds=1/marketProb,odds=Math.min(CONFIG.maxDisplayedOdds,Math.max(1.01,rawOdds));return `<div class="odds-row"><b>${i+1}</b><div><strong>${esc(x.name)}</strong>${i===0?'<div class="favourite">FAVOURITE</div>':''}</div><span class="odds">$${odds.toFixed(2)}</span></div>`}).join("")}
function playerName(id){const p=state.players[id]||{};return p.full_name||[p.first_name,p.last_name].filter(Boolean).join(" ")||`Player ${id}`}
function tradeAssets(t){const by={};mids(t).forEach(id=>by[id]=[]);Object.entries(t.adds||{}).forEach(([pid,rid])=>{const mid=t.roster_owner_map?.[String(rid)];if(mid&&by[mid])by[mid].push({type:"player",id:pid,name:playerName(pid),value:Number(state.playerAverages[pid]||0)})});(t.draft_picks||[]).forEach(p=>{const mid=t.roster_owner_map?.[String(p.owner_id)];if(!mid||!by[mid])return;const round=Number(p.round),value=round===1?23.5:round===2?5:0,season=p.season||"Future";by[mid].push({type:"pick",name:`${season} Round ${round} Pick`,value})});return by}
function tradeValue(t){return Object.values(tradeAssets(t)).flat().reduce((s,a)=>s+a.value,0)}
function renderTradeWeek(){const sevenDays=state.trades.filter(t=>t.created>=Date.now()-7*864e5),pool=sevenDays.length?sevenDays:state.trades.slice(0,20),t=[...pool].sort((a,b)=>tradeValue(b)-tradeValue(a))[0];if(!t){$("tradeOfWeek").innerHTML="No trade available";return}const sides=Object.entries(tradeAssets(t)).slice(0,3),html=sides.map(([mid,assets])=>`<div class="trade-side"><strong>${esc(state.managers.get(mid)?.name||"Former manager")} receives</strong>${assets.length?assets.map(a=>`<div class="trade-player"><span>${esc(a.name)}</span></div>`).join(""):'<div class="trade-player"><span>No listed assets</span></div>'}</div>`).join('<div class="trade-arrow">⇄</div>');$("tradeOfWeek").classList.remove("loading");$("tradeOfWeek").innerHTML=`<div class="trade-feature clean-trade">${html}<div class="trade-date-block"><span>SELECTED BY TOTAL VALUE EXCHANGED</span><strong>${fmt(t.created)}</strong></div></div>`}
function renderHeatmap(){const teams=[...state.managers.values()],mat={};state.trades.forEach(t=>{const ids=mids(t);for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const k=[ids[i],ids[j]].sort().join("|");mat[k]=(mat[k]||0)+1}});const pairs=[];for(let i=0;i<teams.length;i++)for(let j=i+1;j<teams.length;j++){const a=teams[i],b=teams[j],count=mat[[a.id,b.id].sort().join("|")]||0;pairs.push({a,b,count})}pairs.sort((a,b)=>b.count-a.count||a.a.name.localeCompare(b.a.name));const max=Math.max(...pairs.map(x=>x.count),1);$("tradeHeatmap").classList.remove("loading");$("tradeHeatmap").innerHTML=`<div class="partner-grid">${pairs.map((p,i)=>`<article class="partner-card" style="--heat:${Math.max(.08,p.count/max)}"><div class="partner-rank">${i+1}</div><div class="partner-names"><strong>${esc(p.a.name)}</strong><span>↔</span><strong>${esc(p.b.name)}</strong></div><div class="partner-total"><strong>${p.count}</strong><span>trade${p.count===1?'':'s'}</span></div></article>`).join("")}</div>`}
function renderBlock(){const moved={};state.trades.forEach(t=>Object.keys(t.adds||{}).forEach(id=>moved[id]=(moved[id]||0)+1));const rows=Object.entries(moved).sort((a,b)=>b[1]-a[1]).slice(0,8);$("tradeBlock").classList.remove("loading");$("tradeBlock").innerHTML=rows.length?rows.map(([id,n],i)=>`<div class="rank-item"><b>${i+1}</b><div><strong>${esc(playerName(id))}</strong><div class="meta">Moved more than anyone wants to admit</div></div><span class="power-score">${n}x</span></div>`).join(""):'<div class="loading">No player movement yet</div>'}
function longestDrought(){return [...ranked('all')].sort((a,b)=>a.count-b.count)[0]}
function renderRecords(){const biggest=[...state.trades].sort((a,b)=>(Object.keys(b.adds||{}).length+(b.draft_picks||[]).length)-(Object.keys(a.adds||{}).length+(a.draft_picks||[]).length))[0],day={};state.trades.forEach(t=>{const k=new Date(t.created).toDateString();day[k]=(day[k]||0)+1});const peak=Object.entries(day).sort((a,b)=>b[1]-a[1])[0]||['—',0],active=ranked('all')[0],drought=longestDrought(),cards=[['Most active ever',active?.name||'—',`${active?.count||0} trades`],['Largest trade',biggest?`${Object.keys(biggest.adds||{}).length} players + ${(biggest.draft_picks||[]).length} picks`:'—',biggest?fmt(biggest.created):''],['Most trades in one day',`${peak[1]} trades`,peak[0]],['Longest trade drought',drought?.name||'—',`${drought?.count||0} all-time trades`]];$("leagueRecords").classList.remove("loading");$("leagueRecords").innerHTML=cards.map(x=>`<div class="record"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></div>`).join('')}
function renderTable(){const ws=['14','28','90','all'],cs=Object.fromEntries(ws.map(w=>[w,counts(w)])),r=ranked(state.selectedWindow),max=Object.fromEntries(ws.map(w=>[w,Math.max(...Object.values(cs[w]),0)]));$("scorecardBody").innerHTML=r.map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.name)}</b></td>${ws.map(w=>`<td class="${cs[w][x.id]===max[w]&&max[w]>0?'top-value':''}">${cs[w][x.id]||0}</td>`).join('')}</tr>`).join('')}
function renderRecent(){const r=state.trades.slice(0,10);$("recentTrades").classList.remove("loading");$("recentTrades").innerHTML=r.map(t=>`<article class="trade-card"><div class="trade-date">${fmt(t.created)} · ${esc(t.season_label||'')}</div><div class="trade-teams">${mids(t).map(id=>esc(state.managers.get(id)?.name||'Former manager')).join(' ↔ ')}</div><div class="trade-meta">${Object.keys(t.adds||{}).length} player moves · ${(t.draft_picks||[]).length} picks</div></article>`).join('')||'<div class="loading">No trades</div>'}
function renderAll(){renderSummary();renderLeaderboard();renderPower();renderOdds();renderTradeWeek();renderHeatmap();renderBlock();renderRecords();renderTable();renderRecent()}
async function loadSeason(id){const [league,users,rosters]=await Promise.all([getJSON(`${CONFIG.api}/league/${id}`,true),getJSON(`${CONFIG.api}/league/${id}/users`,true),getJSON(`${CONFIG.api}/league/${id}/rosters`,true)]);if(!league||!users||!rosters)return null;const ownerByRoster={};rosters.forEach(r=>{if(r.owner_id!=null)ownerByRoster[String(r.roster_id)]=String(r.owner_id)});const rounds=Array.from({length:CONFIG.roundsToCheck},(_,i)=>i+1),weeks=await limitedMap(rounds,8,async wk=>{const [tx,match]=await Promise.all([getJSON(`${CONFIG.api}/league/${id}/transactions/${wk}`,true),getJSON(`${CONFIG.api}/league/${id}/matchups/${wk}`,true)]);const trades=(tx||[]).filter(t=>t.type==='trade'&&(!t.status||t.status==='complete')).map(t=>{const ids=new Set((t.roster_ids||[]).map(String));Object.values(t.adds||{}).forEach(x=>ids.add(String(x)));Object.values(t.drops||{}).forEach(x=>ids.add(String(x)));(t.draft_picks||[]).forEach(p=>{if(p.owner_id!=null)ids.add(String(p.owner_id));if(p.previous_owner_id!=null)ids.add(String(p.previous_owner_id))});return {...t,manager_ids:[...ids].map(r=>ownerByRoster[r]).filter(Boolean),roster_owner_map:ownerByRoster,season_label:`${league.season} season`,league_id:id}});const matchups=(match||[]).map(x=>({...x,week:wk}));return{trades,matchups}});return{league,users,rosters,ownerByRoster,trades:weeks.flatMap(x=>x?.trades||[]),matchups:weeks.flatMap(x=>x?.matchups||[])}}
async function load(){$("refreshBtn").disabled=true;$("statusText").textContent='Connecting to Sleeper…';try{const [bundles,players]=await Promise.all([Promise.all(CONFIG.leagueIds.map(loadSeason)),getJSON(`${CONFIG.api}/players/nba`,true)]),valid=bundles.filter(Boolean),cur=valid.find(x=>String(x.league.league_id)===CONFIG.currentLeagueId)||valid[0];state.bundles=valid;state.league=cur.league;state.currentUsers=cur.users;state.currentRosters=cur.rosters;state.players=players||{};buildManagers();const unique=new Map();valid.flatMap(x=>x.trades).forEach(t=>unique.set(t.transaction_id||`${t.league_id}-${t.created}`,t));state.trades=[...unique.values()].sort((a,b)=>(b.created||0)-(a.created||0));prepareModels();renderAll();$("statusText").textContent=`Live · ${valid.length} seasons loaded · model: ${state.modelBundle?.league?.season||'current'}`}catch(e){console.error(e);$("statusText").textContent='Could not load Sleeper data'}finally{$("refreshBtn").disabled=false}}
document.querySelectorAll('.window-btn').forEach(b=>b.addEventListener('click',()=>{state.selectedWindow=b.dataset.window;document.querySelectorAll('.window-btn').forEach(x=>x.classList.toggle('active',x===b));renderSummary();renderLeaderboard();renderTable()}));$("refreshBtn").addEventListener('click',load);load();
